### ISSUE TITLE
Can generate error when using !postmap on a non-mindustry-discord server

### ISSUE THREAD

**Issue by Arkanic** [Anuken/CoreBot#24]
Using !postmap on a discord server that isn't a mindustry official one (in this case #social) generates an error

![image](https://user-images.githubusercontent.com/50847107/127448771-b40ca145-8047-41e4-a9f1-4e4fd969d6fc.png)

**Comment by Anuken** [comment]
CoreBot has no support for other servers, everything is hard-coded to use Mindustry's. It cannot be invited anywhere else. Any instances running somewhere else are *forks* with modified code; I am not responsible for them.

It's also worth noting that the stack trace shown contains very outdated code.
