### ISSUE TITLE
Core doesn't resolve pre-Erekir .msch files

### ISSUE THREAD

**Issue by RusLeonid** [Anuken/CoreBot#36]
![IMG_20220511_161305](https://user-images.githubusercontent.com/81614288/167858545-43adc224-db8e-4549-84ef-149f2e9f43cd.jpg)
Corebot displays v7-erekir .msch files properly,
but doesn't display v135 .msch files.

**Comment by Anuken** [comment]
Fixed, power nodes specifically were crashing.
