### ISSUE TITLE
Whitelist discord.id

### ISSUE THREAD

**Issue by TheMrAlbert** [Anuken/CoreBot#41]
Is a profile viewing in web.
![image](https://github.com/Anuken/CoreBot/assets/44728043/eb18bf86-2302-4d6c-b1bb-533bcc1e3acf)
![image](https://github.com/Anuken/CoreBot/assets/44728043/edb89804-b010-4434-b0de-4e23ee8c5b31)

**Comment by Anuken** [comment]
fixed
