### ISSUE TITLE
Reacting "❌️" to a message in maps channel doesnt delete

### ISSUE THREAD

**Issue by JasonP01** [Anuken/CoreBot#42]
https://github.com/Anuken/CoreBot/blob/284d87701ade34b34fa0539f61fd3fcdeafb81e0/src/corebot/Messages.java#L723

The discord ❌️ emoji is not compatible with the ❌️ unicode emoji and therefore isn't applicable as a reaction.

Changing it to search for "x" is better as thats the emoji's name

**Comment by Anuken** [comment]
1. This is CoreBot source code, not Ranai source code.
2. What you're saying is false.
3. The ❌️ reaction works for me, I just tested it - the map is deleted. If the discord emoji was, as you say, "incompatible", my code wouldn't work *at all*.

**Comment by JasonP01** [comment]
I have 2 links that prove otherwise 
https://discord.com/channels/391020510269669376/416719902641225732/1294269491747754008
https://discord.com/channels/391020510269669376/416719902641225732/1294189868641030221

**Comment by JasonP01** [comment]
I cant replicate those 2 however, but they happened
